"""add policies table

Revision ID: 24bf7a57f408
Revises: 5a574cfc286f
Create Date: 2026-09-20 18:40:41.778844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24bf7a57f408'
down_revision = '5a574cfc286f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimum_recovery_probability', sa.Float(), nullable=False),
    sa.Column('maximum_retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('maximum_auto_retry_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('escalation_threshold', sa.Float(), nullable=False),
    sa.Column('high_value_threshold', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('allowed_payment_methods', sa.JSON(), nullable=False),
    sa.Column('stop_after_success', sa.Boolean(), nullable=False),
    sa.Column('stop_after_max_retries', sa.Boolean(), nullable=False),
    sa.Column('stop_for_low_probability', sa.Boolean(), nullable=False),
    sa.Column('stop_for_high_value_without_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_actions_payment_link_id'), ['payment_link_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_actions_payment_link_id'))

    op.drop_table('policies')
    # ### end Alembic commands ###
