"""Initial RecoverAI schema

Revision ID: 5a574cfc286f
Revises: 
Create Date: 2026-09-05 22:11:45.816214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a574cfc286f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('customer_segment', sa.String(length=50), nullable=False),
    sa.Column('customer_since', sa.DateTime(), nullable=False),
    sa.Column('successful_payments', sa.Integer(), nullable=False),
    sa.Column('failed_payments', sa.Integer(), nullable=False),
    sa.Column('historical_success_rate', sa.Float(), nullable=False),
    sa.Column('customer_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_customer_id'), ['customer_id'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('merchant_category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=150), nullable=True),
    sa.Column('transaction_timestamp', sa.DateTime(), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_id'), ['transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_timestamp'), ['transaction_timestamp'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_check', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('payment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=150), nullable=True),
    sa.Column('response_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_attempts_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('recovery_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('recovery_probability', sa.Float(), nullable=False),
    sa.Column('revenue_at_risk', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('guardrail_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_actions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('recovery_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('recovery_action_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recovery_action_id'], ['recovery_actions.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recovery_action_id')
    )
    with op.batch_alter_table('recovery_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_outcomes_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recovery_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_outcomes_transaction_id'))

    op.drop_table('recovery_outcomes')
    with op.batch_alter_table('recovery_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_actions_transaction_id'))

    op.drop_table('recovery_actions')
    with op.batch_alter_table('payment_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_attempts_transaction_id'))

    op.drop_table('payment_attempts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_decision_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_customer_id'))

    op.drop_table('customers')
    # ### end Alembic commands ###
